
target_compile_definitions(${PROJECT_NAME} PRIVATE HZ_LIB_EXPORT)
if(WIN32)
set_target_properties(${PROJECT_NAME} PROPERTIES 
    RUNTIME_OUTPUT_DIRECTORY_DEBUG ${PROJECT_DESTINATION_DIR}/bin
    LIBRARY_OUTPUT_DIRECTORY_DEBUG ${PROJECT_DESTINATION_DIR}/${PROJECT_NAME}/lib
    ARCHIVE_OUTPUT_DIRECTORY_DEBUG ${PROJECT_DESTINATION_DIR}/${PROJECT_NAME}/lib
    RUNTIME_OUTPUT_DIRECTORY_RELEASE ${PROJECT_DESTINATION_DIR}/bin
    LIBRARY_OUTPUT_DIRECTORY_RELEASE ${PROJECT_DESTINATION_DIR}/${PROJECT_NAME}/lib
    ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${PROJECT_DESTINATION_DIR}/${PROJECT_NAME}/lib
    OUTPUT_NAME "$<IF:$<CONFIG:Debug>,${PROJECT_NAME}d,${PROJECT_NAME}>")

set(CMAKE_INSTALL_PREFIX ${PROJECT_DESTINATION_DIR}/installed/)
endif()

install(TARGETS ${PROJECT_NAME}
    EXPORT ${PROJECT_NAME}Targets
    LIBRARY DESTINATION lib
    ARCHIVE DESTINATION lib
    RUNTIME DESTINATION bin
    INCLUDES DESTINATION include
)

install(FILES
    ${PROJECT_NAME}/include/*.hpp
    DESTINATION ${PROJECT_NAME}/include/${PROJECT_NAME}
)

install(FILES
    CommonDef/include/CommonDef/*.h
    DESTINATION ${PROJECT_NAME}/include/CommonDef
)

install(EXPORT ${PROJECT_NAME}Targets
    FILE ${PROJECT_NAME}Config.cmake
    NAMESPACE ${PROJECT_NAME}::
    DESTINATION lib/cmake/${PROJECT_NAME}
)
