
set(${PROJECT_DESTINATION_DIR} ${CMAKE_SOURCE_DIR})
target_compile_definitions(${PROJECT_NAME} PRIVATE HZ_LIB_EXPORT)
if(WIN32)
set_target_properties(${PROJECT_NAME} PROPERTIES 
    RUNTIME_OUTPUT_DIRECTORY_DEBUG ${PROJECT_DESTINATION_DIR}/bin
    LIBRARY_OUTPUT_DIRECTORY_DEBUG ${PROJECT_DESTINATION_DIR}/${PROJECT_NAME}/lib
    ARCHIVE_OUTPUT_DIRECTORY_DEBUG ${PROJECT_DESTINATION_DIR}/${PROJECT_NAME}/lib
    RUNTIME_OUTPUT_DIRECTORY_RELEASE ${PROJECT_DESTINATION_DIR}/bin
    LIBRARY_OUTPUT_DIRECTORY_RELEASE ${PROJECT_DESTINATION_DIR}/${PROJECT_NAME}/lib
    ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${PROJECT_DESTINATION_DIR}/${PROJECT_NAME}/lib
    OUTPUT_NAME "$<IF:$<CONFIG:Debug>,${PROJECT_NAME}d,${PROJECT_NAME}>")
endif()

include(CMakePackageConfigHelpers)
include(GNUInstallDirs)

install(TARGETS ${PROJECT_NAME}
    EXPORT ${PROJECT_NAME}Targets
    LIBRARY DESTINATION ${PROJECT_NAME}/${CMAKE_INSTALL_LIBDIR}
    ARCHIVE DESTINATION ${PROJECT_NAME}/${CMAKE_INSTALL_LIBDIR}
    RUNTIME DESTINATION ${PROJECT_NAME}/${CMAKE_INSTALL_BINDIR}
    INCLUDES DESTINATION ${PROJECT_NAME}/${CMAKE_INSTALL_INCLUDEDIR}/${PROJECT_NAME} 
)
# export(EXPORT ${PROJECT_NAME}Targets          # ← 保持一致
#        FILE "${PROJECT_DESTINATION_DIR}//HzLoggerTargets.cmake"
#        NAMESPACE HzLogger::)
# 安装头文件
install(DIRECTORY include/
    DESTINATION ${PROJECT_NAME}/include/${PROJECT_NAME}
    FILES_MATCHING PATTERN "*.h" PATTERN "*.hpp"
)
# 生成配置文件
configure_package_config_file(
    "${CMAKE_CURRENT_SOURCE_DIR}/cmake/${PROJECT_NAME}Config.cmake.in"
    "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}Config.cmake"
    INSTALL_DESTINATION ${PROJECT_NAME}/${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}
)

# 生成版本文件
write_basic_package_version_file(
    "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}ConfigVersion.cmake"
    VERSION ${PROJECT_VERSION}
    COMPATIBILITY AnyNewerVersion
)

# 安装配置文件
install(FILES
    "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}Config.cmake"
    "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}ConfigVersion.cmake"
    DESTINATION ${PROJECT_NAME}/${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}
)

# 安装导出目标
install(EXPORT ${PROJECT_NAME}Targets
    FILE ${PROJECT_NAME}Targets.cmake
    NAMESPACE ${PROJECT_NAME}::
    DESTINATION ${PROJECT_NAME}/${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}
)